apiVersion: v1
kind: Service
metadata:
  name: multi-svc
spec:
  selector:
    app: myweb
  ports:
    - targetPort: 8080
      port: 80
      protocol: TCP
      name: http

    - targetPort: 443
      port: 443
      protocol: TCP
      name: https
