apiVersion: v1
kind: Service
metadata:
  name: sts-service
spec:
  clusterIP: None
  selector:
    app: stsweb
  ports:
    - port: 80
      targetPort: 8080
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-pod
spec:
  replicas: 3
  serviceName: sts-service
  selector:
    matchLabels:
      app: stsweb
  template:
    metadata:
      labels:
        app: stsweb
    spec:
      containers:
        - name: webserver
          image: ghcr.io/c1t1d0s7/go-myweb
          ports:
            - containerPort: 8080
