apiVersion: v1
kind: Pod
metadata:
  name: myweb-pod
  labels:
    app: myweb
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command: 
            - pwd
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
