apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod
spec:
  containers:
    - name: mynapp
      image: c1t1d0s7/myweb
      livenessProbe:
        httpGet:
          path: /
          port: 8080
      ports:
        - containerPort: 8080
          protocol: TCP
