apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mynapp
              image: busybox
              command: ["sleep", "70"]
