apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-basic
spec:
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: test
          image: nginx

