apiVersion: batch/v1
kind: Job
metadata:
  name: basic-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mynapp
          image: busybox
          command: ["sleep", "60"]
