apiVersion: batch/v1
kind: Job
metadata:
  name: multi-job
spec:
  completions: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mynapp
          image: busybox
          command: ["sleep", "10"]
