apiVersion: batch/v1
kind: Job
metadata:
  name: para-job
spec:
  parallelism: 3
  completions: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mynapp
          image: busybox
          command: ["sleep", "10"]
