apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-exp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - myweb
          - mydb
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myweb
    spec:
      containers:
        - name: myapp-container
          image: nginx
          imagePullPolicy: IfNotPresent

