apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myweb
    spec:
      containers:
        - name: myapp-container
          image: busybox
          command: ["sleep", "20"]

